name: env
channels:
  - defaults
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - python=3.11.5
  - asttokens==2.4.1
  - certifi==2024.7.4
  - charset-normalizer==3.3.2
  - comm==0.2.2
  - contourpy==1.2.1
  - cycler==0.12.1
  - decorator==5.1.1
  - executing==2.0.1
  - fonttools==4.53.1
  - idna==3.7
  - ipython==8.26.0
  - ipywidgets==8.1.3
  - jedi==0.19.1
  - jupyterlab_widgets==3.0.11
  - kiwisolver==1.4.5
  - matplotlib-inline==0.1.7
  - numpy==2.0.1
  - packaging==24.1
  - pandas==2.2.2
  - parso==0.8.4
  - pexpect==4.9.0
  - pillow==10.4.0
  - plotly==5.23.0
  - prompt_toolkit==3.0.47
  - ptyprocess==0.7.0
  - pure_eval==0.2.3
  - Pygments==2.18.0
  - pyparsing==3.1.2
  - python-dateutil==2.9.0.post0
  - pytz==2024.1
  - requests==2.32.3
  - seaborn==0.13.2
  - six==1.16.0
  # - stack-data==0.6.3
  - tenacity==9.0.0
  - traitlets==5.14.3
  - typing_extensions==4.12.2
  - urllib3==2.2.2
  - wcwidth==0.2.13
  - widgetsnbextension==4.0.11
  - pip:
    - stack-data==0.6.3
    - tzdata==2024.1
    - matplotlib==3.9.0



    
